# Generated by Django 4.2.1 on 2023-05-08 01:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('IN-PROGRESS', 'IN-PROGRESS'), ('COMPLETED', 'COMPLETED'), ('QUEUED', 'QUEUED'), ('FAILED', 'FAILED')], max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.BooleanField(null=True)),
                ('details', models.TextField(null=True)),
                ('proof_image', models.BooleanField(default=False)),
                ('url_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='webcheck.urlcheck')),
            ],
        ),
    ]
